Sonarcloud configuration
PriceScraper/backend pull request #10
Opened 2023-04-18 11:02 UTC by TimTrademark

Resolves #2 
- Added configuration for sonarcloud code analysis

2023-04-18 18:37 UTC, bavodaniels requested changes
not seeing anything happening in sonarcloud

also a bit weird that the application properties are changed for this ticket
(no need to change this)

2023-04-19 06:56 UTC, TimTrademark commented
> 

I think that's because it will only activate on sonarcloud once it gets pushed onto the main branch, the changes in the properties are because I branched from the db config branch, I'll make sure to remove those. Thanks for the feedback.

2023-04-19 12:13 UTC, stijn-schack requested changes

2023-04-19 12:13 UTC, stijn-schack commented on .github/workflows/build.yml
> +          mvn clean install
This `mvn clean install` should be removed, since it was added to troubleshoot integration with sonarcloud.

2023-04-19 14:15 UTC, stijn-schack approved these changes

2023-04-20 06:48 UTC, merged