feat: Convential commits action
PriceScraper/backend pull request #11
Opened 2023-04-18 11:14 UTC by SanderCC

Workflows of push will only work if commit has the correct format

2023-04-18 15:15 UTC, stijn-schack requested changes

2023-04-18 15:15 UTC, stijn-schack commented on git-conventional-commits.yaml
> +  ## GitHub
Please remove lines of code/config in comments.

2023-04-18 15:15 UTC, stijn-schack commented on .github/workflows/convential-commits-action.yml
> +      - uses: actions/checkout@v2
This line triggers a warning in the check, action should be updated to the latest version.

2023-04-19 08:23 UTC, bavodaniels approved these changes

2023-04-19 08:54 UTC, merged